#
#
#说明：
# 
# '删除在github空间的老内扣' 删除12小时之前的所有扣款，保留没效，一删除就会删除时间段的超时时间全部删除
#
# '删除自动发布的老提示'每次启动都可以，设置保留数
#
#下面的开关控制，仅在手动按钮启动时生效，定时启动默认全开


名称：删除
在：
  工作流调度：
    输入：
      删除旧工作流：
        description : '删除github空间旧扣'
        要求：假
        default : ' true '            #删除github空间旧（假=关闭开启）（false=关闭）
      删除旧版本：
        描述：《删除旧的发布》
        要求：假
        default : ' true '            #删除旧的发布（true=开启）（false=关闭）

#  时间表：
#     - 定时任务：0 7 * * 6

环境：
  OLDER_WORKFLOW :真
  OLDER_RELEASES :真

工作：
  del_runs：
    运行：Ubuntu-20.04
    名称：删除工作流运行
    步骤：
    
      -名称：删除在github空间的老码头
        用途：Matraks/delete-workflow-runs@main
        如果：env.OLDER_WORKFLOW == '真' || （github.event.inputs.delete-older-workflow == 'true'）
        与：
          令牌：${{ github.token }}
          存储库：${{ github.repository }}       
          保留天数：0.5
          keep_minimum_runs : 0
    
      -名称：删除自动发布的老提示
        用途：dev-drprasad/delete-older-releases@master
        如果：env.OLDER_RELEASES == 'true' || （github.event.inputs.delete-older-releases == 'true'）
        与：
          keep_latest : 0          #保留多少个发布不删除
          delete_tags :真
        环境：
          GITHUB_TOKEN : ${{ secrets.REPO_TOKEN }}
